[project]
name = "mvp-machine-learning-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.1"

dependencies = [
    "tensorflow==2.15.0",
    "nltk==3.8.1",
    "numpy==1.23.5",
    "fastapi==0.95.1",
    "uvicorn==0.22.0",
    "python-multipart==0.0.6"
]

#Dependências opcionais
#Streamlit: streamlit==1.22.0
